# This workflow will generate a distribution and upload it to PyPI

name: Publish Alpha Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'neon_diana_utils/version.py'
      - '**/Chart.yaml'

jobs:
  publish_alpha_release:
    uses: neongeckocom/.github/.github/workflows/publish_alpha_release.yml@FEAT_ExtraReleaseScripts
    secrets: inherit
    with:
      version_file: "neon_diana_utils/version.py"
      publish_prerelease: true
      publish_pypi: false
      # TODO: Enable PyPI
      on_version_change: "scripts/sync_chart_app_versions.py"